resilience4j:
  circuitbreaker:
    instances:
      demoCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      demoRetry:
        maxAttempts: 3
        waitDuration: 300ms